name = "InsomniacsRest"
author = "CrismPack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f9de9508e6a7a1f012f77acb6d33156fdaf06097b18e4ada5136bf00841f45"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
