name = "Insomniacs Rest"
author = "CrismPack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb5e15242ef69654437ebebe6bf5ff9b8b797f4851f001c3537a0cbc4cbb8015"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
