name = "InsomniacsRest"
author = "CrismPack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2f78d649f4498863125a0e1816679920d5242feef256571127dbe012decd97a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
